server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://${study.datasource.ip}:3306/${study.datasource.study.name}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Hongkong&allowMultiQueries=true
    username: ${study.datasource.username}
    password: ${study.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.dll.code: debug
#    com.zledu.race: debug


mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.dll.code.entity
  global-config:
    db-config:
      id-type: INPUT

#zledu:
#  swagger:
#    enabled: true
#    title: 文件中心
#    description: 文件中心接口文档
#    version: 1.0
#    base-package: study.code.dll.controller
feign:
  hystrix:
    enabled: true




